export const typingStrings = [
	"Hello ツ",
	"Welcome to my website",
	"I am Krishan",
	"I am a Software Engineer",
	"I am a Web Developer",
	"I am an App Developer",
	"I am a Teaching Assistant",
	"I am an all rounder Computer Scientist",
];

export const TimeLineData = [
	{ year: 2017, text: 'Started my journey' },
	{ year: 2018, text: 'Worked as a freelance developer' },
	{ year: 2019, text: 'Founded JavaScript Mastery' },
	{ year: 2020, text: 'Shared my projects with the world' },
	{ year: 2021, text: 'Started my own platform' },
];

export const acomplishments = [
	{ number: 20, text: 'Open Source Projects' },
	{ number: 1000, text: 'Students' },
	{ number: 1900, text: 'Github Followers' },
	{ number: 5000, text: 'Github Stars' },
];

// image: '/images/1.png',
export const projects = [
	{
		id: 0,
		title: 'Vioo App',
		description:
			'App designed and developed for Vioo completly from scratch as part of Contract work. Connected with databases, restful apis and webhooks, developed using Flutter.',
		commits: 170,
		branches: 15,
		image: '/images/vioo.png',
		languages: ['Flutter', 'Dart', 'PHP'],
		time: '',
		teamSize: '',
		url: 'https://github.com/KrishanSritharar2000/Modelling-Quantum-Gravity',
		live: '',
	},
	{
		id: 1,
		title: 'Tutor Me',
		description:
			'Online tutoring platform',
		commits: 200,
		branches: 1,
		image: '/images/1.png',
		languages: ['Python', 'Processing'],
		time: '',
		teamSize: '',
		url: 'https://github.com/KrishanSritharar2000/Modelling-Quantum-Gravity',
		live: '',
	},
	{
		id: 2,
		title: 'WACC',
		description:
			'Compiler',
		commits: 50,
		branches: 1,
		image: '/images/1.png',
		languages: ['Python', 'Processing'],
		time: '',
		teamSize: '',
		url: 'https://github.com/KrishanSritharar2000/Modelling-Quantum-Gravity',
		live: '',
	},
	{
		id: 3,
		title: 'PintOS',
		description:
			'Operating system developed using C',
		commits: 40,
		branches: 1,
		image: '/images/1.png',
		languages: ['Python'],
		time: '',
		teamSize: '',
		url: 'https://github.com/KrishanSritharar2000/Mental-Maths-Game',
		live: '',
	},
	{
		id: 4,
		title: 'CFlow',
		description:
			'A TensorFlow equivalent library written from scratch in C. Developers can use CFlow to make neural networks with many input and output heads.',
		commits: 58,
		branches: 1,
		image: '/images/1.png',
		languages: ['C', 'Makefile'],
		time: '',
		teamSize: '',
		url: 'https://github.com/KrishanSritharar2000/CFlow',
		live: '',
	},
	{
		id: 5,
		title: 'Royal Chat',
		description:
			'[RoyalChat - IC Hack 20 Project] A real-time messaging web app designed to link people together anonymously on a predetermined topic without fear of judgement or trolled.',
		commits: 122,
		branches: 1,
		image: '/images/1.png',
		languages: ['Python', 'Go', 'HTML'],
		time: '',
		teamSize: '',
		url: 'https://github.com/ICHACK2020/Royal-Chat',
		live: '',
	},
	{
		id: 6,
		title: 'Modelling Quantum Gravity',
		description:
			'Gold CREST Project on "Developing Computational Methods of Modelling Quantum Gravity". A Monte Carlo random walk 🎲🚶 simulation research project created using Python and Processing.',
		commits: 50,
		branches: 1,
		image: '/images/1.png',
		languages: ['Python', 'Processing'],
		time: '',
		teamSize: '',
		url: 'https://github.com/KrishanSritharar2000/Modelling-Quantum-Gravity',
		live: '',
	},
	{
		id: 7,
		title: 'Mental Maths Game',
		description:
			'A graphical platformer-style game to develop your mental maths skills 🔢. Drive 🚗through the levels, collecting all the coins 💰 as you go along and answering all the questions ❔ as quick as you can ⏳.',
		commits: 40,
		branches: 1,
		image: '/images/1.png',
		languages: ['Python'],
		time: '',
		teamSize: '',
		url: 'https://github.com/KrishanSritharar2000/Mental-Maths-Game',
		live: '',
	},
];