export const typingStrings = [
	"Hello ツ",
	"Welcome to my website",
	"I am Krishan",
	"I am a Software Engineer",
	"I am a Web Developer",
	"I am an App Developer",
	"I am a Teaching Assistant",
	"I am an all rounder Computer Scientist",
];

export const TimeLineData = [
	{ year: 2015, text: 'Started my journey by discovering programming using Kodu Game Lab' },
	{ year: 2016, text: 'Created my first app: a Flappy Bird replica built using BuildBox' },
	{ year: 2017, text: 'Achieved straight A*s at GCSE - Highest mark in my school' },
	{ year: 2018, text: 'Developed a Monte Carlo Simulation for CREST project' },
	// { year: 2019, text: 'Created a Mental Maths platformer game for helping student\'s learn' },
	{ year: 2019, text: 'Started my Computing degree at Imperial College London' },
	{ year: 2020, text: 'Started workin with the awesome concept of Concurrency' },
	// { year: 2020, text: 'Attened my first Hackathon at IC Hack 20' },
	{ year: 2021, text: 'Head of Mobile Development at Vioo Inc' },
];

export const acomplishments = [
	{ number: 'First Class Honours', text: 'in First and Second years of undergraduate degree' },
	{ number: '1600+', text: 'Lifetime commits' },
	{ number: 1900, text: 'Github Followers' },
	{ number: '3 Students', text: 'I tutor for GCSE Maths, Computing and Physics' },
];

// image: '/images/1.png',
export const projects = [
	{
		id: 0,
		title: 'Vioo App',
		description:
			'App designed and developed for Vioo completly from scratch as part of Contract work. Connected with databases, restful apis and webhooks, developed using Flutter.',
		commits: 170,
		branches: 15,
		image: '/images/vioo.png',
		languages: ['Flutter', 'Dart', 'PHP'],
		time: '',
		teamSize: '',
		url: 'https://github.com/KrishanSritharar2000/Modelling-Quantum-Gravity',
		live: '',
	},
	{
		id: 1,
		title: 'Tutor Me',
		description:
			'Online Tutoring Platform web app created using JavaScript and Kotlin',
		commits: 200,
		branches: 1,
		image: '/images/tutorme.png',
		languages: ['Python', 'Processing'],
		time: '',
		teamSize: '',
		url: 'https://github.com/KrishanSritharar2000/Modelling-Quantum-Gravity',
		live: '',
	},
	{
		id: 2,
		title: 'WACC',
		description:
			'Fully functional compiler written completely from scratch using Kotli',
		commits: 50,
		branches: 1,
		image: '/images/1.png',
		languages: ['Python', 'Processing'],
		time: '',
		teamSize: '',
		url: 'https://github.com/KrishanSritharar2000/Modelling-Quantum-Gravity',
		live: '',
	},
	{
		id: 3,
		title: 'PintOS',
		description:
			'Concurrent, VM supported OS framework extended using C',
		commits: 40,
		branches: 1,
		image: '/images/1.png',
		languages: ['Python'],
		time: '',
		teamSize: '',
		url: 'https://github.com/KrishanSritharar2000/Mental-Maths-Game',
		live: '',
	},
	{
		id: 4,
		title: 'CFlow',
		description:
			'A TensorFlow equivalent library written from scratch in C. Developers can use CFlow to make neural networks with many input and output heads.',
		commits: 58,
		branches: 1,
		image: '/images/1.png',
		languages: ['C', 'Makefile'],
		time: '',
		teamSize: '',
		url: 'https://github.com/KrishanSritharar2000/CFlow',
		live: '',
	},
	{
		id: 5,
		title: 'Royal Chat',
		description:
			'A real-time messaging web app designed to link people together anonymously on a predetermined topic without fear of judgement or trolled.',
		commits: 122,
		branches: 1,
		image: '/images/1.png',
		languages: ['Python', 'Go', 'HTML'],
		time: '',
		teamSize: '',
		url: 'https://github.com/ICHACK2020/Royal-Chat',
		live: '',
	},
	{
		id: 6,
		title: 'Modelling Quantum Gravity',
		description:
			'Gold CREST Project on "Developing Computational Methods of Modelling Quantum Gravity". A Monte Carlo random walk 🎲🚶 simulation research project created using Python and Processing.',
		commits: 50,
		branches: 1,
		image: '/images/1.png',
		languages: ['Python', 'Processing'],
		time: '',
		teamSize: '',
		url: 'https://github.com/KrishanSritharar2000/Modelling-Quantum-Gravity',
		live: '',
	},
	{
		id: 7,
		title: 'Mental Maths Game',
		description:
			'A graphical platformer-style game to develop your mental maths skills 🔢. Drive 🚗through the levels, collecting all the coins 💰 as you go along and answering all the questions ❔ as quick as you can ⏳.',
		commits: 40,
		branches: 1,
		image: '/images/1.png',
		languages: ['Python'],
		time: '',
		teamSize: '',
		url: 'https://github.com/KrishanSritharar2000/Mental-Maths-Game',
		live: '',
	},
];